apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results-app
  template:
    metadata:
      labels:
        app: results-app
    spec:
      containers:
        - name: results
          image: results-app:latest
          imagePullPolicy: Never  # car tu le build localement
          ports:
            - containerPort: 3005
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_DB
              value: vote_db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password

