---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: php-vote
spec:
  type: NodePort
  selector:
    app: php-vote
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: node-results
spec:
  type: NodePort
  selector:
    app: node-results
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30005

